# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Mona Framework
tagline:             'Documentation'
description:         'Mona is a framework that integrates components, tools and best practices for rapid application development.'
url:                 https://mantismind.github.io
baseurl:             /mona
paginate:            5

# About/contact
author:
  name:              
  url:               
  email:             

# Custom vars
version:             
